<a href="https://colab.research.google.com/github/sysiphe0/exercise_ml/blob/main/%5Bstats%5D_confusion_matrix_simple_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#iris 데이터세트 만들기
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
iris.data
iris.feature_names
iris.target
iris.target_names


iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df["target"] = iris.target 
iris_df["target_names"] = iris.target_names[iris.target]
iris_df[:5]


#훈련세트, 테스트세트 나누기
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(iris_df, test_size = 0.3)

train_set.shape
test_set.shape


#kNN
import sklearn.neighbors as nn
knn = nn.KNeighborsClassifier(n_neighbors = 1)

#훈련
knn.fit(X=train_set.iloc[:, :-1], y=train_set.target)

#테스트
pred = knn.predict(X=test_set.iloc[:, :-1])


#성능테스트
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#confusion_matrix
#classification_report
c_mat = confusion_matrix(test_set.target.values, pred)
print('\n\nConfusion Matrix\n', c_mat)
print('\n', classification_report(test_set.target.values, pred, target_names=iris.target_names))



Confusion Matrix
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 15]]

               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00        20
   virginica       1.00      1.00      1.00        15

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

