<a href="https://colab.research.google.com/github/sysiphe0/exercise_ml/blob/main/LogisticRegression_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### 참고(출처) : Carl's Tech Bolg (https://wotres.tistory.com/)

In [1]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [3]:
breast_cancer = datasets.load_breast_cancer()
X = breast_cancer.data
y = breast_cancer.target

train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.1, random_state=0)

In [12]:
# C : Inverse of regularization, 절편 없으면 : fit_intercept=False
lor = LogisticRegression(penalty='l2', C=100000, random_state=98709, solver='newton-cg')
lor.fit(train_x, train_y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/optimize.py:212: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


LogisticRegression(C=100000, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=98709, solver='newton-cg', tol=0.0001,
                   verbose=0, warm_start=False)

In [19]:
# 예측
preds = lor.predict(test_x)
preds

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1])

In [22]:
# 예측 확률
preds = lor.predict_proba(test_x)
preds

array([[9.99999785e-01, 2.15114921e-07],
       [4.14329475e-03, 9.95856705e-01],
       [1.24683124e-06, 9.99998753e-01],
       [2.70431569e-04, 9.99729568e-01],
       [1.48140840e-08, 9.99999985e-01],
       [1.06776216e-04, 9.99893224e-01],
       [5.41624192e-08, 9.99999946e-01],
       [3.12164821e-06, 9.99996878e-01],
       [1.24493947e-05, 9.99987551e-01],
       [1.49686263e-10, 1.00000000e+00],
       [6.18878642e-04, 9.99381121e-01],
       [9.09210301e-03, 9.90907897e-01],
       [8.49866166e-09, 9.99999992e-01],
       [6.08149979e-02, 9.39185002e-01],
       [1.11587674e-01, 8.88412326e-01],
       [9.99999877e-01, 1.23161806e-07],
       [5.83496707e-07, 9.99999417e-01],
       [1.00000000e+00, 1.60670355e-15],
       [9.99999941e-01, 5.85399403e-08],
       [1.00000000e+00, 1.27909324e-24],
       [9.99999994e-01, 6.15748303e-09],
       [9.98077879e-01, 1.92212143e-03],
       [1.72778379e-04, 9.99827222e-01],
       [1.55520402e-05, 9.99984448e-01],
       [9.999998

In [23]:
# logit 로짓 값들의 평균
# observation별 logit 값의 평균
# odds 는 실패에 비해 성공할 확률의 비 : p/(1-p)
# odds에 log를 취한값이 바로 로짓 : Log(p)
# 회귀분석의 y=ax+b가 ln(p/1-p) = ax+b 가 된 것 => 즉, 로지스틱 회귀분석은 일반회귀 함수를 로짓으로 변형한 분석법
import math
import numpy as np
arr = []
for pred in preds:
  # 만약에 아주 확률이 1에 가까워 1이 나온다면 최대한 1보다 작은 가장 큰 값 입력
  arr.append(math.log(float(pred[1])/float(1-pred[1])))
print(np.mean(arr))
# 또는
print(np.mean(np.log(preds[:,1]/preds[:,0])))

-0.7913070742709037
-0.7913070742709037


In [30]:
# 가장 영향이 큰(기준 : Odds Ratio) 독립변수 => e의 지수에 해당 변수가 위치하므로 np.exp 를 사용한다.
cols = breast_cancer.feature_names
print(cols[np.exp(lor.coef_).argmax()])

concavity error


In [31]:
# 변수에 대한 계수
lor.coef_

array([[ 2.09739683e+00, -1.80355047e-01,  3.55900294e-01,
        -3.11983971e-02, -2.58219784e+01,  4.93526795e+01,
        -3.23324964e+01, -5.64773096e+01,  2.52736249e+00,
         3.26928313e+00, -1.38543409e+01,  1.54617233e+00,
         2.93823040e+00, -2.88451708e-01, -1.81693523e+01,
         4.07532734e+01,  4.97303471e+01, -1.67553913e+01,
         2.41256779e+01,  9.74603805e+00, -5.11843833e-01,
        -3.98511542e-01, -2.74985881e-01,  1.03998229e-03,
        -5.09329710e+01,  6.04276994e+00, -1.06146865e+01,
        -5.38396257e+01, -1.71602312e+01, -1.39352403e+01]])

In [32]:
# 특정 변수에 대한 오즈비 => 로지스틱 회귀분석에서 오즈비는 np.exp(특정변수의 계수)
np.exp(lor.coef_[0])

array([8.14493966e+00, 8.34973704e-01, 1.42746521e+00, 9.69283251e-01,
       6.10460081e-12, 2.71391595e+21, 9.08186919e-15, 2.96630699e-25,
       1.25204398e+01, 2.62924844e+01, 9.61913920e-07, 4.69347068e+00,
       1.88824025e+01, 7.49422995e-01, 1.28573232e-08, 4.99944479e+17,
       3.95927192e+21, 5.28720348e-08, 3.00364622e+10, 1.70863992e+04,
       5.99389385e-01, 6.71318532e-01, 7.59582847e-01, 1.00104052e+00,
       7.58737860e-23, 4.21057725e+02, 2.45527552e-05, 4.14712993e-24,
       3.52700672e-08, 8.87160204e-07])

In [33]:
# 평균면적이 1 증가할 때마다 유방암에 걸릴 확률이 몇배나 증가한다고 할 수 있는지를 구하라 => mean area에 대한 오즈비를 구하라(Odds Ratio)
# 오즈비는 1증가할 때마다 얼마나 증가하는 지를 보인다. 만약 0,2가 값으로 있다면 minmax를 하는 것이 좋고, 3가지 값이 있다면 one-hot encoder 후 학습시킨뒤 비를 구하면 더 정확함
i = cols.tolist().index('mean area')
np.exp(lor.coef_[0][i])

0.9692832509996638

In [35]:
# 예측확률에 따른 예측치 결정(threshold or cut off value)
pred_pro = np.where(preds[:,1]>0.5, 1, 0)
pred_pro

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1])