<a href="https://colab.research.google.com/github/sysiphe0/exercise_ml/blob/main/LogisticRegression_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### 참고(출처) : Carl's Tech Bolg (https://wotres.tistory.com/)

In [1]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
breast_cancer = datasets.load_breast_cancer()
X = breast_cancer.data
y = breast_cancer.target

train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.1, random_state=0)

In [3]:
# C : Inverse of regularization, 절편 없으면 : fit_intercept=False
lor = LogisticRegression(penalty='l2', C=100000, random_state=98709, solver='newton-cg')
lor.fit(train_x, train_y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/optimize.py:212: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


LogisticRegression(C=100000, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=98709, solver='newton-cg', tol=0.0001,
                   verbose=0, warm_start=False)

In [4]:
# 예측
preds = lor.predict(test_x)
preds

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1])

In [6]:
# 예측 확률
preds = lor.predict_proba(test_x)
#preds

In [28]:
lor.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  341
Model:                          Logit   Df Residuals:                      333
Method:                           MLE   Df Model:                            7
Date:                Sat, 12 Dec 2020   Pseudo R-squ.:                  0.8724
Time:                        22:23:24   Log-Likelihood:                -28.802
converged:                       True   LL-Null:                       -225.66
Covariance Type:            nonrobust   LLR p-value:                 5.325e-81
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           48.1756     18.888      2.551      0.011      11.156      85.195
mean_radius         -1.3953      5.363     -0.260      0.795     -11.908       9.117
mean_texture        -0.4942      0.122     -4.050      0.000      -0.733      -0.255
mean_perimeter       0.1387      0.694      0.200      0.842      -1.221       1.499
mean_area           -0.0164      0.026     -0.642      0.521      -0.067       0.034
mean_smoothness   -170.1488     45.876     -3.709      0.000    -260.064     -80.234
mean_compactness    -8.6134     23.292     -0.370      0.712     -54.265      37.038
mean_concavity     -36.5583     13.127     -2.785      0.005     -62.286     -10.830
====================================================================================

Possibly complete quasi-separation: A fraction 0.42 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [7]:
# logit 로짓 값들의 평균
# observation별 logit 값의 평균
# odds 는 실패에 비해 성공할 확률의 비 : p/(1-p)
# odds에 log를 취한값이 바로 로짓 : Log(p)
# 회귀분석의 y=ax+b가 ln(p/1-p) = ax+b 가 된 것 => 즉, 로지스틱 회귀분석은 일반회귀 함수를 로짓으로 변형한 분석법
import math
import numpy as np
arr = []
for pred in preds:
  # 만약에 아주 확률이 1에 가까워 1이 나온다면 최대한 1보다 작은 가장 큰 값 입력
  arr.append(math.log(float(pred[1])/float(1-pred[1])))
print(np.mean(arr))
# 또는
print(np.mean(np.log(preds[:,1]/preds[:,0])))

-0.7913070742709037
-0.7913070742709037


In [8]:
# 가장 영향이 큰(기준 : Odds Ratio) 독립변수 => e의 지수에 해당 변수가 위치하므로 np.exp 를 사용한다.
cols = breast_cancer.feature_names
print(cols[np.exp(lor.coef_).argmax()])

concavity error


In [9]:
# 변수에 대한 계수
lor.coef_

array([[ 2.09739683e+00, -1.80355047e-01,  3.55900294e-01,
        -3.11983971e-02, -2.58219784e+01,  4.93526795e+01,
        -3.23324964e+01, -5.64773096e+01,  2.52736249e+00,
         3.26928313e+00, -1.38543409e+01,  1.54617233e+00,
         2.93823040e+00, -2.88451708e-01, -1.81693523e+01,
         4.07532734e+01,  4.97303471e+01, -1.67553913e+01,
         2.41256779e+01,  9.74603805e+00, -5.11843833e-01,
        -3.98511542e-01, -2.74985881e-01,  1.03998229e-03,
        -5.09329710e+01,  6.04276994e+00, -1.06146865e+01,
        -5.38396257e+01, -1.71602312e+01, -1.39352403e+01]])

In [10]:
# 특정 변수에 대한 오즈비 => 로지스틱 회귀분석에서 오즈비는 np.exp(특정변수의 계수)
np.exp(lor.coef_[0])

array([8.14493966e+00, 8.34973704e-01, 1.42746521e+00, 9.69283251e-01,
       6.10460081e-12, 2.71391595e+21, 9.08186919e-15, 2.96630699e-25,
       1.25204398e+01, 2.62924844e+01, 9.61913920e-07, 4.69347068e+00,
       1.88824025e+01, 7.49422995e-01, 1.28573232e-08, 4.99944479e+17,
       3.95927192e+21, 5.28720348e-08, 3.00364622e+10, 1.70863992e+04,
       5.99389385e-01, 6.71318532e-01, 7.59582847e-01, 1.00104052e+00,
       7.58737860e-23, 4.21057725e+02, 2.45527552e-05, 4.14712993e-24,
       3.52700672e-08, 8.87160204e-07])

In [11]:
# 평균면적이 1 증가할 때마다 유방암에 걸릴 확률이 몇배나 증가한다고 할 수 있는지를 구하라 => mean area에 대한 오즈비를 구하라(Odds Ratio)
# 오즈비는 1증가할 때마다 얼마나 증가하는 지를 보인다. 만약 0,2가 값으로 있다면 minmax를 하는 것이 좋고, 3가지 값이 있다면 one-hot encoder 후 학습시킨뒤 비를 구하면 더 정확함
i = cols.tolist().index('mean area')
np.exp(lor.coef_[0][i])

0.9692832509996638

In [12]:
# 예측확률에 따른 예측치 결정(threshold or cut off value)
pred_pro = np.where(preds[:,1]>0.5, 1, 0)
pred_pro

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1])

## 통계적으로 유의한 독립변수 찾는 법 (statsmodels, GLM 사용 케이스)

In [17]:
import statsmodels.api as sm
import pandas as pd
breast_cancer = datasets.load_breast_cancer()
X = breast_cancer.data
y = breast_cancer.target
cols = [i.replace(' ','_') for i in breast_cancer.feature_names] + ['y']
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.4, random_state=1234)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [23]:
# 배열합치기 : (hstack - 열(column) 추가, vstack - 행(row) 추가)
train = np.hstack((train_x, train_y.reshape(-1,1)))
test = np.hstack((test_x, test_y.reshape(-1,1)))
train = pd.DataFrame(train, columns=cols)
test = pd.DataFrame(test, columns=cols)

In [26]:
# 20개 넘어가면 잘 안됨
formula = 'y ~ mean_radius + mean_texture + mean_perimeter + mean_area + mean_smoothness + mean_compactness + mean_concavity'
# train
lor = sm.Logit.from_formula(formula, train).fit()
# 요약
print(lor.summary())
# p_value 확인 => 0.05 이하이면 의미있는 변수
print("----------------------")
print(lor.pvalues)
# 계수확인
print("----------------------")
print(lor.params)

Optimization terminated successfully.
         Current function value: 0.084463
         Iterations 11
                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                  341
Model:                          Logit   Df Residuals:                      333
Method:                           MLE   Df Model:                            7
Date:                Sat, 12 Dec 2020   Pseudo R-squ.:                  0.8724
Time:                        22:20:02   Log-Likelihood:                -28.802
converged:                       True   LL-Null:                       -225.66
Covariance Type:            nonrobust   LLR p-value:                 5.325e-81
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           48.1756     18.888      2.551      0.011      11.156      85.195
mean_radiu

In [27]:
# 또 다른 방법. 일반선형 모델인 GLM(Generlize linear Model)에서 이진 분류하면 link function이 Logit되어 Logistic regression 됨
import statsmodels.formula.api as smf
smf.glm(formula, train, family=sm.families.Binomial()).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                      y   No. Observations:                  341
Model:                            GLM   Df Residuals:                      333
Model Family:                Binomial   Df Model:                            7
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -28.802
Date:                Sat, 12 Dec 2020   Deviance:                       57.604
Time:                        22:21:59   Pearson chi2:                     150.
No. Iterations:                    10                                         
Covariance Type:            nonrobust                                         
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           48.1756     18.888      2.551      0.011      11.156      85.195
mean_radius         -1.3953      5.363     -0.260      0.795     -11.908       9.117
mean_texture        -0.4942      0.122     -4.050      0.000      -0.733      -0.255
mean_perimeter       0.1387      0.694      0.200      0.842      -1.221       1.499
mean_area           -0.0164      0.026     -0.642      0.521      -0.067       0.034
mean_smoothness   -170.1488     45.876     -3.709      0.000    -260.064     -80.234
mean_compactness    -8.6134     23.292     -0.370      0.712     -54.265      37.038
mean_concavity     -36.5583     13.127     -2.785      0.005     -62.286     -10.830
====================================================================================
"""